07.10.2021

Reverts ArsenEloglian/21_22-Advanced-Programming-Techniques#4

Revert "Update 07.10.2021"

---

07.10.2021

Segeda Oleksandr 
Lista obecności

[G] Segeda Oleksandr

---

07.10.2021

Artur Oliferuk

---

07.10.2021
DariaHyrenko/tablica.java

Reverts ArsenEloglian/21_22-Advanced-Programming-Techniques#31

Revert "test"

---

Kamil_Olejarz/PESEL.java

poprawa zadania pesel

---

DominikLesniewski/Liczby_pierwsze.cpp

isPrime function: you don't need to declare variable 'test', you can just return true or false;
line 36: 'return 0' not necessary

[KubaKern] DominikLesniewski update Liczby_pierwsze.cpp

---

DominikLesniewski/Parzyste_nieparzyste.cpp

line 7: added space beetween '>>' because code was not compiling
line 22-24: changed loops, because '{}' were not necessary
return 0 not necessary

[KubaKern] DominikLesniewski update Parzyste_nieparzyste

---

KubaKern/CzyUmieszPotegowac/Main.java

- added scanner.close() at the end of the main()

[DominikLesniewski] Kuba Kern's CzyUmieszPotegowac suggested changes

---

KubaKern/BFN1/Main.java

- line 18: int reversed is never used in palindrome function
- line 32: you don't need the variable here
- added scan.close() at the end of the main()

[DominikLesniewski] Kuba Kern's BFN1 suggested changes

---

SegedaOleksandr_plik/Sumy.cpp

[SegedaOleksandr]

---

MateuszGowin/Liczby Pierwsze.cpp

Update Liczby Pierwsze.cpp

---

MateuszGowin/kalkulator.cpp

- consider using switch case instead of spamming if statements (if it was on purpose - please comment, i'd like to know)

[DominikLesniewski] Update kalkulator.cpp

---

WeronikaDemich/Pesel/pesel.cpp

[Kuba Kern] Update pesel.cpp

---

MateuszGowin/kalkulator2.cpp

- consider using switch case instead of spamming if statements (if it was on purpose - please comment, i'd like to know)

[DominikLesniewski] Update kalkulator2.cpp

---

MateuszGowin/suma.cpp

- you can use a much 'cleaner' while loop, w/o the additional if statement

[DominikLesniewski] Update suma.cpp

---

PawelKumorowski/NWW2/nww2.cpp

[Kuba Kern] Update nww2.cpp

---

KamilGajewski/17 Stos/main.cpp

[Weronika Demich] Update Stos

---

Michal_Plewa/cpp/522.cpp

[Kuba Kern] Update 522.cpp

---

DominikLesniewski/Suma.cpp

[Kuba Kern] Update Suma.cpp

---

SegedaOleksandr_plik/Imeniny.cpp

[Kuba Kern] Update Imeniny.cpp

---

MichalSwiac/zad 3.cpp

return 0 not required, deleted empty lines

[Kuba Kern] Update zad 3.cpp

---

KornelMotyka/cw1.cpp

[Kuba Kern] Update cw1.cpp

---

KornelMotyka/NWD.cpp

return 0 in main is not required in c++

[Mateusz Gowin]Update NWD.cpp

---

KamilGajewski/6 BFN1/main.cpp

[Kuba Kern] Update main.cpp

---

DariaHyrenko/tablica.java

[Kuba Kern] Update tablica.java

---

MateuszGowin/StringMerge.cpp

- the exercise is not completed (?)

[DominikLesniewski] Update StringMerge.cpp

---

WeronikaDemich/Pesel/pesel.cpp

return 0 in fuction main is not required

[Michał Plewa] Update pesel.cpp

---

KubaKern/PRIME_T/main.java

- deleted a random newline in the for loop

[DominikLesniewski] PRIME_T small update

---

_the presence of students_/AttendanceList.txt

[Michał Plewa] 02.12.2021 lista obecności

[Michał Plewa] 02.12.2021 lista obecności

---

SegedaOleksandr_plik/Summy.cpp
_the presence of students_/AttendanceList.txt

[Segeda Oleksandr] Lista + Spoj

---

_the presence of students_/AttendanceList.txt

[DominikLesniewski] Attendance 09.12.2021

---

_the presence of students_/AttendanceList.txt

[Segeda Oleksandr] Lista
